exports.majorData =
  [
    {
      id: 'glx',
      name: '管理学',
      imgUrl: 'glx.png',
      imgW: '60rpx',
      imgH: '40rpx',
      show: false
    }, {
      id: 'jjx',
      name: '经济学',
      imgUrl: 'jjx.png',
      imgW: '53rpx',
      imgH: '40rpx',
      show: false
    }, {
      id: 'jyx',
      name: '教育学',
      imgUrl: 'jyx.png',
      imgW: '68rpx',
      imgH: '40rpx',
      show: false
    }, {
      id: 'lx',
      name: '理学',
      imgUrl: 'lx.png',
      imgW: '31rpx',
      imgH: '40rpx',
      show: false
    }, {
      id: 'gx',
      name: '工学',
      imgUrl: 'gx.png',
      imgW: '39rpx',
      imgH: '40rpx',
      show: false
    }, {
      id: 'yx',
      name: '医学',
      imgUrl: 'yx.png',
      imgW: '40rpx',
      imgH: '40rpx',
      show: false
    }, {
      id: 'ysx',
      name: '艺术学',
      imgUrl: 'ysx.png',
      imgW: '47rpx',
      imgH: '40rpx',
      show: false
    }, {
      id: 'fx',
      name: '法学',
      imgUrl: 'fx.png',
      imgW: '45rpx',
      imgH: '40rpx',
      show: false
    }, {
      id: 'wx',
      name: '文学',
      imgUrl: 'wx.png',
      imgW: '28rpx',
      imgH: '40rpx',
      show: false
    }, {
      id: 'nx',
      name: '农学',
      imgUrl: 'nx.png',
      imgW: '30rpx',
      imgH: '40rpx',
      last: true,
      show: false
    }, {
      id: 'lsx',
      name: '历史学',
      imgUrl: 'lsx.png',
      imgW: '50rpx',
      imgH: '40rpx',
      last: true,
      show: false
    }, {
      id: 'zx',
      name: '哲学',
      imgUrl: 'zx.png',
      imgW: '42rpx',
      imgH: '40rpx',
      last: true,
      show: false
    }
  ]
