exports.majorData = 
[
  {
    id: 'sk',
    name: '商科',
    imgUrl: 'sk.png',
    imgW: '32rpx',
    imgH: '52rpx',
    show: false
  }, {
    id: 'gc',
    name: '工程',
    imgUrl: 'gc.png',
    imgW: '40rpx',
    imgH: '39rpx',
    show: false
  }, {
    id: 'zrkx',
    name: '自然科学',
    imgUrl: 'zrkx.png',
    imgW: '44rpx',
    imgH: '48rpx',
    show: false
  }, {
    id: 'shkx',
    name: '社会科学',
    imgUrl: 'shkx.png',
    imgW: '31rpx',
    imgH: '48rpx',
    show: false
  }, {
    id: 'jyx',
    name: '教育学',
    imgUrl: 'jyx.png',
    imgW: '50rpx',
    imgH: '30rpx',
    show: false
  }, {
    id: 'flx',
    name: '法律学',
    imgUrl: 'flx.png',
    imgW: '50rpx',
    imgH: '45rpx',
    show: false
  }, {
    id: 'ggsw',
    name: '公共事务',
    imgUrl: 'ggsw.png',
    imgW: '45rpx',
    imgH: '42rpx',
    show: false
  }, {
    id: 'xwcb',
    name: '新闻传播',
    imgUrl: 'xwcb.png',
    imgW: '43rpx',
    imgH: '43rpx',
    show: false
  }, {
    id: 'ys',
    name: '艺术',
    imgUrl: 'ys.png',
    imgW: '44rpx',
    imgH: '39rpx',
    last: true,
    show: false
  }, {
    id: 'jk',
    name: '健康',
    imgUrl: 'jk.png',
    imgW: '38rpx',
    imgH: '51rpx',
    last: true,
    show: false
  }
]
